### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by MattSurabian** [MattSurabian/grunt_cookbook#3]
Should probably test it...

**Comment by joemckie** [comment]
I'm using it for a new project and it still seems to work as expected. Will notify of any breakages. Thanks for the work!

**Comment by MattSurabian** [comment]
Awesome, thanks @joemckie! I used to work with Chef everyday but now it's more Ansible. I'll have to spend some time to get this on the new hotness and do some kind of TestKitchen thing with the repo. Glad to know it's not broken though!

**Comment by toadkicker** [comment]
Tried it out tonight, got this
code:

```
grunt_cookbook_npm APP_PATH do
  action :task
  task "start"
end
```

result:
`Option action must be equal to one of: nothing, install, install!  You passed :task.`

This is in AWS Opsworks fwiw

**Comment by joemckie** [comment]
@toadkicker, you're using the wrong method to fire Grunt tasks. Try using `grunt_cookbook_grunt` instead.

**Comment by MattSurabian** [comment]
Aye, this only provides support for `npm install` because that command is needed to install grunt in a project. There is no support in this cookbook for running other npm scripts.

**Comment by toadkicker** [comment]
Thanks gents! I was in the weeds trying to get Chef to start my app, ended up going to bash to make it happen. Not what I wanted but it does the job. Other than that this cookbook worked perfectly for me.

**Comment by MattSurabian** [comment]
Closing as it sounds like this cookbook is working. Going to open a new issue to add testing!
